baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Jake Callahan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2
        - name: CV
          url: cv.pdf
          weight: 3 

params:
    description: "U Arizona PhD student"
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jake Callahan
          subtitle: "I am a 1st-year PhD student in the Program in Applied Mathematics at the University of Arizona. 
                     Prior to enrolling at Arizona, I completed my Master's degree in Mathematics at Brigham Young University,
          where I worked under [Dr. Jared Whitehead](https://tsunami.byu.edu/jared-p-whitehead) on the [TsunamiBayes project](https://tsunami.byu.edu/whitehead-lab).

          <br><br>
          I am interested in uncertainty quantification, with particular interest in Bayesian optimal experimental design, estimation of information, and MCMC techniques.
          Applications of my work include geophysics (earthquakes, seismic sensor placement, tsunamis) and political science (detection of gerrymandering in state redistricting plans).
          <br><br>
          In my spare time I enjoy spending time in the mountains (backpacking when it's warm and skiing when it's cold), playing music, and spending time with my family." 
          imageUrl: "headshot.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Jake Callahan
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: CV
              url: cv.pdf
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: Email
          url: mailto:jakecallahan@math.arizona.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=aqzYn14AAAAJ
        - name: GitHub
          url: https://github.com/jcallahan4
        - name: LinkedIn
          url: https://linkedin.com/in/jake-callahan
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jake Callahan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
