baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: Clayton Williams
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: papers/
          weight: 1
        - name: Teaching
          url: courses/
          weight: 2
        - name: CV
          url: cv.pdf
          weight: 3 

params:
    description: "U Illinois Urbana-Champaign Ph.D. student"
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Clayton Williams
          subtitle: "I'd like to improve my academic site so this is a test" 
          imageUrl: "headshot.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Clay Williams
          buttons:
            - name: Research
              url: papers/
            - name: Teaching
              url: courses/
            - name: CV
              url: cv.pdf
            # - name: Newsletter
            #   url:
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
    socialIcons:
        - name: Email
          url: mailto:cw78@illinois.edu
        - name: Google Scholar
          url: https://sites.google.com/view/clayw/home
#        - name: GitHub
#          url: https://github.com/jcallahan4
        - name: LinkedIn
          url: https://www.linkedin.com/in/clay-williams/
#        - name: Location
#          url: location/
#        - name: Office Hours
#          url: officehours/


    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Clay Williams"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
